#!/bin/bash

GREEN="\e[32m"
RED="\e[31m"
RESET_COLOR="\e[0m"

trap 'tput cnorm; rm -f "${OUTPUT_FILES[@]}"' EXIT

SCRIPTS=("npm run format:check" "npm run lint" "npm run type-check")
PIDS=()
EXIT_CODES=()
OUTPUT_FILES=()
SOME_FAILED=0

REFRESH_SECONDS=1

for SCRIPT in "${SCRIPTS[@]}"; do
  OUTPUT_FILE=$(mktemp -t ci.XXXXXX)
  FORCE_COLOR=1 $SCRIPT > "$OUTPUT_FILE" 2>&1 &
  PIDS+=("$!")
  OUTPUT_FILES+=("$OUTPUT_FILE")
done

tput civis

while true; do
  SCRIPT_INDEX=0

  for SCRIPT in "${SCRIPTS[@]}"; do
    kill -0 "${PIDS[$SCRIPT_INDEX]}" 2>/dev/null
    KILL_CODE=$?

    if [[ $KILL_CODE -ne 0 ]]; then
      if [[ ! -v EXIT_CODES[$SCRIPT_INDEX] ]]; then
        wait "${PIDS[$SCRIPT_INDEX]}"
        EXIT_CODES[$SCRIPT_INDEX]=$?
      fi

      if [[ ${EXIT_CODES[$SCRIPT_INDEX]} -eq 0 ]]; then
        echo -e "\r\e[K$GREEN$SCRIPT succeeded$RESET_COLOR"
      else
        echo -e "\r\e[K$RED$SCRIPT failed$RESET_COLOR"
        SOME_FAILED=1
      fi
    else
       echo -e "\r\e[K$SCRIPT running.."
    fi
    SCRIPT_INDEX=$((SCRIPT_INDEX + 1))
  done

  if [[ ${#EXIT_CODES[@]} -eq ${#SCRIPTS[@]} ]]; then
    break;
  fi

  for SCRIPT in "${SCRIPTS[@]}"; do
    echo -ne "\e[1A"
  done

  sleep "$REFRESH_SECONDS"
done

tput cnorm

SCRIPT_INDEX=0
for SCRIPT in "${SCRIPTS[@]}"; do
  if [[ ${EXIT_CODES[$SCRIPT_INDEX]} -ne 0 ]]; then
    cat "${OUTPUT_FILES[$SCRIPT_INDEX]}"
  fi
  SCRIPT_INDEX=$((SCRIPT_INDEX + 1))
done

if [[ $SOME_FAILED -eq 0 ]]; then
  if git diff --cached --quiet && git diff --quiet; then
    gum confirm "All checks passed! Push and merge PR?" && git push && gh pr merge -md
  else
    git status
  fi
fi
