#!/bin/bash

random_id () {
  echo "$$-$RANDOM"
}

trap "tput cnorm" EXIT

SCRIPTS=("npm run format:check" "npm run lint" "npm run type-check")
PIDS=()
EXIT_CODES=()
OUTPUT_FILES=()
SOME_FAILED=0
REFRESH_SECONDS=1

for SCRIPT in "${SCRIPTS[@]}"; do
  OUTPUT_FILE="$(random_id).txt"
  FORCE_COLOR=1 $SCRIPT > $OUTPUT_FILE 2>&1 &
  PIDS+=($!)
  OUTPUT_FILES+=($OUTPUT_FILE)
done

GREEN="\e[32m"
RED="\e[31m"
RESET_COLOR="\e[0m"

tput civis

while true; do
  SCRIPT_INDEX=0

  for SCRIPT in "${SCRIPTS[@]}"; do
    kill -0 ${PIDS[$SCRIPT_INDEX]} 2>/dev/null
    KILL_CODE=$?

    if [[ $KILL_CODE -ne 0 ]]; then
      if [[ ! -v EXIT_CODES[$SCRIPT_INDEX] ]]; then
        wait ${PIDS[$SCRIPT_INDEX]}
        EXIT_CODES[$SCRIPT_INDEX]=$?
      fi

      if [[ ${EXIT_CODES[$SCRIPT_INDEX]} -eq 0 ]]; then
        echo -e "\r\e[K$GREEN$SCRIPT succeded$RESET_COLOR"
      else
        SOME_FAILED=1
        echo -e "\r\e[K$RED$SCRIPT failed$RESET_COLOR"
      fi
    else
       echo -e "\r\e[K$SCRIPT running.."
    fi
    SCRIPT_INDEX=$((SCRIPT_INDEX + 1))
  done

  if [[ ${#EXIT_CODES[@]} -eq ${#SCRIPTS[@]} ]]; then
    break;
  fi

  for SCRIPT in "${SCRIPTS[@]}"; do
    echo -ne "\e[1A"
  done

  sleep $REFRESH_SECONDS

  SCRIPT_INDEX=0
done

tput cnorm

